---
- name: install lighttpd web server
  become: yes
  apt:
    name: lighttpd
    state: latest
    upadate_cache: yes

- name: Generate the configuration file
  template: 
    src: myconfig.j2
    dest: /etc/lighttpd/lighttpd.conf
    owner: root
    group: root
    mode: 0664

  vars:
    server_port: 80


- name: start the lighttpd service
  become: yes
  service:
    name: lighttpd
    state: started